# Generated by Django 4.2.26 on 2025-11-11 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("consoles", "Consolas"),
                    ("gaming_pcs", "PCs gamer"),
                    ("peripherals", "Periféricos"),
                    ("components", "Componentes"),
                    ("accessories", "Merch y accesorios"),
                ],
                default="consoles",
                max_length=30,
            ),
        ),
    ]
