# Generated by Django 4.2.26 on 2025-11-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
